### PR TITLE
Implemented refresh callback upon return of user action.

### PR DESCRIPTION
**Pull request by ExtraBB**
Refresh get requests are now done when a user performs one of the supported actions. (Issue cash, create IOU, Transfer IOU, Settle IOU)

### CODE REVIEW

**Review by joeldudley — APPROVED** [review]

**Comment by joeldudley** [comment]
Thanks, this is great :) I've added your name to our contributors list here: https://github.com/corda/corda/blob/master/CONTRIBUTORS.md. Let me know if you want me to change how you're listed.

**Comment by ExtraBB** [comment]
Awesome, thanks! :) It's fine like this.

**Comment by joeldudley** [comment]
@ExtraBB Hi Bruno. Because this contribution is part of the Corda GitHub organisation, I need to check whether your contribution is in accordance with the Developer's Certificate of Origin - see https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin.

If it is, can you leave a comment stating that “I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).”

**Comment by ExtraBB** [comment]
Ah alright! I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) .

**Comment by ExtraBB** [comment]
@joeldudleyr3 Would it be possible to change how I'm listed to: "Bruno dos Santos Carvalhal (Ordina Nederland)"? This is my full name and company I work for.

**Comment by joeldudley** [comment]
Done 🙂

**Pull request merged**
